
var trans={'à':'a','á':'a','â':'a','ã':'a','ä':'a','å':'a','æ':'ae','ç':'c','è':'e','é':'e','ê':'e','ë':'e','ě':'e','ę':'e','ð':'d','ì':'i','í':'i','î':'i','ï':'i','ł':'l','ñ':'n','ń':'n','ň':'n','ò':'o','ó':'o','ô':'o','õ':'o','ö':'o','ø':'o','ù':'u','ú':'u','û':'u','ü':'u','ş':'s','š':'s','ý':'y','ÿ':'y','ž':'z','þ':'th','ß':'ss','À':'A','Á':'A','Â':'A','Ã':'A','Ä':'A','Å':'A','Æ':'AE','Ç':'C','È':'E','É':'E','Ê':'E','Ë':'E','Ě':'E','Ę':'E','Ð':'D','Ì':'I','Í':'I','Î':'I','Ï':'I','Ł':'L','Ñ':'N','Ń':'N','Ň':'N','Ò':'O','Ó':'O','Ô':'O','Õ':'O','Ö':'O','Ø':'O','Ù':'U','Ú':'U','Û':'U','Ü':'U','Ş':'S','Š':'S','Ý':'Y','Ÿ':'Y','Ž':'Z','Þ':'TH'};function set_to_lower_case_no_accents(text){"use strict";var char;var text_new='';var i;for(i=0;i<text.length;i=i+1){char=text.substr(i,1);if(trans[char]){text_new+=trans[char];}else{text_new+=char;}}
return text_new.toLowerCase();}
function SET_OverviewTable($table){"use strict";var that=this;var i;this.myDebug=true;this.$myTable=$table;$table.find('thead tr.filter').each(function(){$(this).css('display','table-row');});this.myColumnHandlers=[];var column_index=0;$table.find('thead tr.header').find('th').each(function(header_index,th){var attr;var classes;var span;that.myColumnHandlers[column_index]=null;attr=$(th).attr('class');classes=attr.split(' ');for(i=0;i<classes.length;i=i+1){if(classes[i].substr(0,10)==='data-type-'){var column_type=classes[i].substr(10);if(SET_OverviewTable.ourColumnTypeHandlers[column_type]){that.myColumnHandlers[column_index]=new SET_OverviewTable.ourColumnTypeHandlers[column_type]();}}}
if(!that.myColumnHandlers[column_index]){that.myColumnHandlers[column_index]=new SET_NoneColumnTypeHandler();}
that.myColumnHandlers[column_index].initFilter(that,$table,header_index);that.myColumnHandlers[column_index].initSort(that,$table,header_index,column_index);span=$(this).attr('colspan');if(span){column_index=column_index+parseFloat(span);}else{column_index=column_index+1;}});}
SET_OverviewTable.prototype.mergeInfo=function(sort_info,column_sort_info){"use strict";if(sort_info.length===0){column_sort_info.sort_order=1;sort_info[0]=column_sort_info;}else{if(column_sort_info.sort_order!==false&&sort_info[column_sort_info.sort_order-1]){sort_info[column_sort_info.sort_order-1].sort_direction=column_sort_info.sort_direction;}else{column_sort_info.sort_order=sort_info.length;sort_info[sort_info.length]=column_sort_info;}}
return sort_info;};SET_OverviewTable.prototype.getSortOrder=function($header,infix){"use strict";var attr;var classes;var sort_order_class;var i;var order=false;attr=$header.attr('class');classes=attr.split(' ');for(i=0;i<classes.length;i=i+1){sort_order_class='sort-order'+infix;if(classes[i].substr(0,sort_order_class.length)===sort_order_class){order=parseInt(classes[i].substr(sort_order_class.length),10);}}
return order;};SET_OverviewTable.prototype.getSortDirection=function($header,infix){"use strict";if($header.hasClass('sorted'+infix+'desc')){return'desc';}
if($header.hasClass('sorted'+infix+'asc')){return'asc';}
return'';};SET_OverviewTable.prototype.sort=function(event,$header,that,header_index,column_index){"use strict";var sort_info;var sort_column_info;var time;var total_time;if(this.myDebug){SET_OverviewTable.log('Start sort:');time=new Date();total_time=time;}
sort_info=this.getSortInfo();if(this.myDebug){SET_OverviewTable.benchmark('Get all sort info - ',time);time=new Date();}
sort_column_info=this.getColumnSortInfo(event,$header,header_index,column_index);if(this.myDebug){SET_OverviewTable.benchmark('Get info about current column - ',time);time=new Date();}
this.cleanSortClasses();if(this.myDebug){SET_OverviewTable.benchmark('Reset column headers - ',time);time=new Date();}
if(!event.ctrlKey){sort_info=this.mergeInfo([],sort_column_info);if(this.myDebug){SET_OverviewTable.benchmark('Merge info - ',time);time=new Date();}
this.sortSingleColumn(sort_info[0],that);if(this.myDebug){SET_OverviewTable.benchmark('Sorted by one column - ',time);time=new Date();}}else{sort_info=this.mergeInfo(sort_info,sort_column_info);if(this.myDebug){SET_OverviewTable.benchmark('Merge info - ',time);time=new Date();}
if(sort_info.length===1){this.sortSingleColumn(sort_info[0],that);if(this.myDebug){SET_OverviewTable.benchmark('Sorted by one column - ',time);time=new Date();}}else{this.sortMultiColumn(sort_info);if(this.myDebug){SET_OverviewTable.benchmark('Sorted by '+sort_info.length+' column - ',time);time=new Date();}}}
this.addSortInfo(sort_info);if(this.myDebug){SET_OverviewTable.benchmark('Added info to table head - ',time);time=new Date();}
this.applyZebraTheme();if(this.myDebug){SET_OverviewTable.benchmark('Apply zebra theme - ',time);SET_OverviewTable.benchmark('Finished for - ',total_time);}};SET_OverviewTable.prototype.getSortInfo=function(){"use strict";var column_index=0;var columns_info=[];var span;var sort_order;var sort_direction;var that=this;var colspan;this.$myTable.find('thead tr.header').find('th').each(function(header_index,th){var $th=$(th);span=$(this).attr('colspan');if(!span||span==='1'){sort_order=that.getSortOrder($th,'-');if(sort_order){columns_info[sort_order-1]={column_index:column_index,header_index:header_index,sort_order:sort_order,sort_direction:that.getSortDirection($th,'-'),infix:'-',colspan:1,offset:0};}}else if(span==='2'){if($th.hasClass('sort-1')){sort_order=that.getSortOrder($th,'-1-');if(sort_order){columns_info[sort_order-1]={column_index:column_index,header_index:header_index,sort_order:sort_order,sort_direction:that.getSortDirection($th,'-1-'),infix:'-1-',colspan:2,offset:0};}}
if($th.hasClass('sort-2')){sort_order=that.getSortOrder($th,'-2-');if(sort_order){columns_info[sort_order-1]={column_index:column_index,header_index:header_index,sort_order:that.getSortDirection($th,'-2-'),sort_direction:sort_direction,infix:'-2-',colspan:2,offset:1};}}}
if(span){column_index=column_index+parseFloat(span);}else{column_index=column_index+1;}});return columns_info;};SET_OverviewTable.prototype.getColumnSortInfo=function(event,$header,header_index,column_index){"use strict";var span;var column_info={};var width_col1;var width_col2;var width_header;var $table=this.$myTable;var diff;var x;function getFlipSortDirection($table,$header,infix){var sort_direction;sort_direction=$table.getSortDirection($header,infix);if(sort_direction==='desc'||sort_direction===''){return'asc';}
return'desc';}
column_info.column_index=column_index;column_info.header_index=header_index;span=$header.attr('colspan');if(!span||span==='1'){column_info.infix='-';column_info.colspan=1;column_info.offset=0;column_info.sort_order=this.getSortOrder($header,column_info.infix);column_info.sort_direction=getFlipSortDirection(this,$header,column_info.infix);}else if(span==='2'){if($header.hasClass('sort-1')&&$header.hasClass('sort-2')){x=event.pageX-$header.offset().left;width_col1=$table.find('tbody > tr:visible:first > td:eq('+column_index+')').outerWidth();width_col2=$table.find('tbody > tr:visible:first > td:eq('+(column_index+1)+')').outerWidth();width_header=$header.outerWidth();diff=width_header-width_col1-width_col2;if(x<((2*width_col1-diff)/2)){column_info.infix='-1-';column_info.colspan=2;column_info.offset=0;column_info.sort_order=this.getSortOrder($header,column_info.infix);column_info.sort_direction=getFlipSortDirection(this,$header,column_info.infix);}else if(x>((2*width_col1+diff)/2)){column_info.infix='-2-';column_info.colspan=2;column_info.offset=1;column_info.sort_order=this.getSortOrder($header,column_info.infix);column_info.sort_direction=getFlipSortDirection(this,$header,column_info.infix);}}else if($header.hasClass('sort-1')){column_info.infix='-1-';column_info.colspan=2;column_info.offset=0;column_info.sort_order=this.getSortOrder($header,column_info.infix);column_info.sort_direction=getFlipSortDirection(this,$header,column_info.infix);}else if($header.hasClass('sort-2')){column_info.infix='-2-';column_info.colspan=2;column_info.offset=1;column_info.sort_order=this.getSortOrder($header,column_info.infix);column_info.sort_direction=getFlipSortDirection(this,$header,column_info.infix);}}
return column_info;};SET_OverviewTable.prototype.cleanSortClasses=function(){"use strict";var that=this;var i;for(i=0;i<that.myColumnHandlers.length;i=i+1){that.$myTable.children('thead').find('th').removeClass('sort-order-'+i);}
that.$myTable.children('thead').find('th').removeClass('sorted-asc').removeClass('sorted-desc');that.$myTable.children('thead').find('th > span').removeClass('sorted-asc').removeClass('sorted-desc');};SET_OverviewTable.prototype.addSortInfo=function(sort_info){"use strict";var order;var $header;var i;for(i=0;i<sort_info.length;i=i+1){order=i+1;$header=this.$myTable.children('thead').find('tr.header').find('th').eq(sort_info[i].header_index);$header.addClass('sort-order'+sort_info[i].infix+order);$header.addClass('sorted'+sort_info[i].infix+sort_info[i].sort_direction);}};SET_OverviewTable.prototype.applyZebraTheme=function(){"use strict";var even=true;this.$myTable.children('tbody').children('tr').each(function(){var $this=$(this);if(this.style.display!=='none'){if(even===true){$this.removeClass('odd').addClass('even');}else{$this.removeClass('even').addClass('odd');}
even=!even;}});};SET_OverviewTable.prototype.sortSingleColumn=function(sorting_info,column){"use strict";var column_index;var rows;var sort_direction;var i;var tbody;if(!sorting_info.infix){return;}
if(sorting_info.sort_direction==='asc'){sort_direction=1;}else{sort_direction=-1;}
column_index=sorting_info.column_index+sorting_info.offset;rows=this.$myTable.children('tbody').children('tr').get();for(i=0;i<rows.length;i=i+1){var cell=rows[i].cells[column_index];rows[i].sortKey=column.getSortKey(cell);}
rows.sort(function(row1,row2){return sort_direction*column.compareSortKeys(row1.sortKey,row2.sortKey);});tbody=this.$myTable.children('tbody')[0];for(i=0;i<rows.length;i=i+1){rows[i].sortKey=null;tbody.appendChild(rows[i]);}};SET_OverviewTable.prototype.sortMultiColumn=function(sorting_info){"use strict";var dir;var cmp;var i,j;var sort_func='';var rows;var cell;var column_handler;var tbody;var that=this;var multi_cmp=null;sort_func+="multi_cmp = function (row1, row2) {\n";sort_func+="  var cmp;\n";for(i=0;i<sorting_info.length;i=i+1){dir=1;if(sorting_info[i].sort_direction==='desc'){dir=-1;}
sort_func+="  cmp = that.myColumnHandlers["+
sorting_info[i].column_index+"].compareSortKeys(row1.sortKey["+
i+"], row2.sortKey["+
i+"]);\n";sort_func+="  if (cmp !== 0) {\n";sort_func+="    return cmp * "+dir+";\n";sort_func+="  }\n";}
sort_func+="  return 0;\n";sort_func+="};\n";rows=this.$myTable.children('tbody').children('tr').get();for(i=0;i<rows.length;i=i+1){rows[i].sortKey=[];for(j=0;j<sorting_info.length;j=j+1){column_handler=this.myColumnHandlers[sorting_info[j].column_index];cell=rows[i].cells[sorting_info[j].column_index];rows[i].sortKey[j]=column_handler.getSortKey(cell);}}
eval(sort_func);rows.sort(multi_cmp);tbody=this.$myTable.children('tbody')[0];for(i=0;i<rows.length;i=i+1){rows[i].sortKey=null;tbody.appendChild(rows[i]);}};SET_OverviewTable.prototype.filter=function(){"use strict";var filters=[];var i;var that=this;for(i=0;i<this.myColumnHandlers.length;i=i+1){if(this.myColumnHandlers[i]&&this.myColumnHandlers[i].startFilter()){filters[i]=this.myColumnHandlers[i];}else{filters[i]=null;}}
if(filters.length===0){this.$myTable.children('tbody').children('tr').show();that.applyZebraTheme();}else{this.$myTable.children('tbody').children('tr').hide();this.$myTable.children('tbody').children('tr').each(function(){var i;var show=1;var $this=$(this);for(i=0;i<filters.length;i+=1){if(filters[i]&&!filters[i].simpleFilter(this.cells[i])){show=0;break;}}
if(show===1){$this.show();that.applyZebraTheme();}});}};SET_OverviewTable.registerColumnTypeHandler=function(column_type,handler){"use strict";SET_OverviewTable.ourColumnTypeHandlers[column_type]=handler;};SET_OverviewTable.filterTrigger=function(event){"use strict";event.data.table.filter(event,event.data.element);};SET_OverviewTable.benchmark=function(s,d){"use strict";SET_OverviewTable.log(s+(new Date().getTime()-d.getTime())+"ms");};SET_OverviewTable.log=function(s){"use strict";if(console!=="undefined"&&console.debug!=="undefined"){console.log(s);}else{alert(s);}};SET_OverviewTable.ourTables=[];SET_OverviewTable.ourColumnTypeHandlers={};SET_OverviewTable.registerTable=function(selector){"use strict";$(selector).each(function(){var $this=$(this);if($this.is('table')){SET_OverviewTable.ourTables[SET_OverviewTable.ourTables.length]=new SET_OverviewTable($this);}else{$this.find('table').each(function(){SET_OverviewTable.ourTables[SET_OverviewTable.ourTables.length]=new SET_OverviewTable($(this));});}});};function SET_NoneColumnTypeHandler(){"use strict";}
SET_NoneColumnTypeHandler.prototype.startFilter=function(){"use strict";return false;};SET_NoneColumnTypeHandler.prototype.initSort=function(overview_table,$table,header_index,column_index){"use strict";return false;};SET_NoneColumnTypeHandler.prototype.initFilter=function(overview_table,$table,header_index,column_index){"use strict";var $cell;$cell=$table.children('thead').find('tr.filter').find('td').eq(header_index);$cell.html('');$cell.width($cell.css('width'));};SET_OverviewTable.registerColumnTypeHandler('none',SET_NoneColumnTypeHandler);function SET_TextColumnTypeHandler(){"use strict";this.$myInput=null;this.myFilterValue=null;}
SET_TextColumnTypeHandler.prototype.startFilter=function(){"use strict";this.myFilterValue=this.$myInput.val();return(this.myFilterValue!=='');};SET_TextColumnTypeHandler.prototype.simpleFilter=function(table_cell){"use strict";var value;value=this.extractForFilter(table_cell);return(value.indexOf(this.myFilterValue)!==-1);};SET_TextColumnTypeHandler.prototype.initSort=function(overview_table,$table,header_index,column_index){"use strict";var that=this;var $header;$header=$table.children('thead').find('tr.header').find('th').eq(header_index);if($header.hasClass('sort')||$header.hasClass('sort-1')||$header.hasClass('sort-2')){$header.click(function(event){overview_table.sort(event,$header,that,header_index,column_index);});}};SET_TextColumnTypeHandler.prototype.initFilter=function(overview_table,$table,header_index){"use strict";var that=this;this.$myInput=$table.children('thead').find('tr.filter').find('td').eq(header_index).find('input');this.$myInput.val('');this.$myInput.keyup(function(event){if(event.keyCode===27){that.$myInput.val('');}});this.$myInput.keyup({table:overview_table,element:this.$myInput},SET_OverviewTable.filterTrigger);this.$myInput.width(this.$myInput.closest('td').width()-
parseInt(this.$myInput.css('margin-left'),10)-
parseInt(this.$myInput.css('border-left-width'),10)-
parseInt(this.$myInput.css('border-right-width'),10)-
parseInt(this.$myInput.css('margin-right'),10));this.$myInput.css('visibility','visible');};SET_TextColumnTypeHandler.prototype.extractForFilter=function(table_cell){"use strict";return set_to_lower_case_no_accents($(table_cell).text());};SET_TextColumnTypeHandler.prototype.getSortKey=function(table_cell){"use strict";return set_to_lower_case_no_accents($(table_cell).text());};SET_TextColumnTypeHandler.prototype.compareSortKeys=function(value1,value2){"use strict";if(value1<value2){return-1;}
if(value1>value2){return 1;}
return 0;};SET_OverviewTable.registerColumnTypeHandler('text',SET_TextColumnTypeHandler);SET_OverviewTable.registerColumnTypeHandler('email',SET_TextColumnTypeHandler);function SET_NumericColumnTypeHandler(){"use strict";}
SET_NumericColumnTypeHandler.prototype=Object.create(SET_TextColumnTypeHandler.prototype);SET_NumericColumnTypeHandler.constructor=SET_NumericColumnTypeHandler;SET_NumericColumnTypeHandler.prototype.getSortKey=function(table_cell){"use strict";var exp;exp=/[\d\.,\-\+]/g;return parseInt(exp.exec($(table_cell).text()).replace(',','.'),10);};SET_NumericColumnTypeHandler.prototype.compareSortKeys=function(row1,row2){"use strict";if(row1.sortKey===row2.sortKey){return 0;}
if(row1.sortKey===""&&!isNaN(row2.sortKey)){return-1;}
if(row2.sortKey===""&&!isNaN(row1.sortKey)){return 1;}
return row1.sortKey-row2.sortKey;};SET_OverviewTable.registerColumnTypeHandler('numeric',SET_NumericColumnTypeHandler);